### ISSUE TITLE
Q: SECCOMP_RET_USER_NOTIF use?

### ISSUE THREAD

**Issue by topimiettinen** [seccomp/libseccomp#143]
Linux 5.0 improves seccomp by adding `SECCOMP_RET_USER_NOTIF` return code. This allows a helper process to examine in more detail the parameters of the seccomp'ed syscall. For example, structures which are referred only by pointers in multiplexed syscalls in i386 could be examined (for example with ptrace or reading `/proc/pid/mem`) to determine if the syscall should fail or not. This would allow libseccomp to hide differences in system call handling between architectures and make previously broken filters (on at least i386) to work.

From libseccomp user perspective this could be seen both as good and bad. On the other side implementing such demultiplexing in libseccomp would be ideal, as no changes to user code would be needed and filters (for example on socket syscalls) would start working on all architectures. Implementing a helper process for `SECCOMP_RET_USER_NOTIF` without libseccomp, but while still using it for other filters, seems like a layering violation. But it could be also surprising if libseccomp suddenly started launching helper processes. Some kind of opt-in to enable this or leaving helper process creation to user side might be a good idea, though then changes would be needed.

Using `SECCOMP_RET_USER_NOTIF` and examining the memory of the calling process could be also used to implement other new filtering features.

How do you see this from libseccomp design point of view?

**Comment by pcmoore** [comment]
Hi @topimiettinen.

As an aside, please don't think I've forgotten about your range checking RFE, it has just fallen onto the back burner.  I do apologize for the delay on that.

The `SECCOMP_RET_USER_NOTIF` capability is interesting, and there has been some desire to enable something like this going back the the early days of libseccomp with the `SCMP_ACT_TRACE` code.  My gut feeling is to start simple and just allow libseccomp users to set the appropriate flags, likely through a filter attribute, and then provide a mechanism for the caller to get the notification fd.  We could also provide a mechanism where we libseccomp would use a caller supplied callback, but that introduces it's own challenges.

However, everything is still on the table at this point, so comments/suggestions are welcome.  I believe @tych0 even has some libseccomp patches in the works, it might be good to see what he has in mind before we make any hard decisions.

**Comment by tych0** [comment]
I was actually working on this just last night :). I'm having problems figuring out how to use the test suite, but you can see my draft patches here:

https://github.com/tych0/libseccomp/tree/user-notification

I hadn't thought about exposing the "grabbing memory from the process" bits; I was mostly thinking of libseccomp as a thin wrapper around seccomp.

**Comment by pcmoore** [comment]
Thanks for the pointer @tych0.  If you're stuck on the tests and want some help/pointers you know where to find me.

Also, would you mind sending a PR for the first couple patches that change the macros/#defines?  We're going to cut a new libseccomp release "real soon now" and it would be nice to have those in the release.

**Comment by topimiettinen** [comment]
The thin wrapper approach would not help much in the demultiplexing case because system call filtering logic would have to be reimplemented in the helper process by either libseccomp or its user. For other use cases it may well be the right approach.

Demultiplexing socket calls needs also fd injection capability, is someone working on that?

**Comment by tych0** [comment]
No, nobody is. I proposed some patches, but they were nack'd because of the required changes to the VFS :). I'm sure it would be possible to do (and in particular I've talked to several people who want it), but nobody has yet agreed that they'd take up the torch with me on lkml :)

As for demuxing, I'm not exactly sure what you'd want there. Some kind of process object wrapper or something? It really seems like the pid is the right thing.

I could imagine something like:

`int seccomp_open_memory(struct seccomp_notif *req);`

which does the ID_VALID checking necessary to make things safe. But that's not exactly demuxing.

**Comment by pcmoore** [comment]
Something to keep in mind with respect to the multiplexed x86 socket calls, direct versions were added back in Linux v4.3 and we already have support for that in libseccomp.  In addition to, and maybe instead of, worrying about socketcall(), it might be a good idea to ensure the various libc variants make use of the direct socket syscalls when they are available.

As far as older, "enterprise" kernels are concerned, that problem should fix itself in another year or two.

**Comment by tych0** [comment]
Now I'm completely confused :). What do we mean by demuxing here? I thought it was trying to figure out which process an event belongs to, since an fd can send events for multiple processes.

The socket issue is just that there's no notification-api way to pass fds back. It can be done through ptrace, though.

**Comment by tych0** [comment]
https://github.com/seccomp/libseccomp/pull/144 is the PR for the header updates

**Comment by pcmoore** [comment]
> #144 is the PR for the header updates

Thanks!

> Now I'm completely confused :). What do we mean by demuxing here?

Based on the original comment from @topimiettinen, I thought he was talking about the socket and ipc syscall multiplexing that was done on x86 (and a few other arches).

**Comment by topimiettinen** [comment]
Yes, I was thinking about socket and IPC syscalls, also I think mmap() also had a struct passing variant. If all those are indeed gone, there's no need to invent complex demultiplexers anymore, great! When the direct versions are available, I suppose the old versions can be blacklisted as obsolete (so that the filters can't be bypassed) but I think this would be out of scope for libseccomp.

**Comment by topimiettinen** [comment]
For x86, old_mmap (syscall 90) has been replaced by mmap2 (192), which no longer uses structs. Socketcall multiplexer at 102 was replaced by direct socket syscalls 359 onwards. For IPC indeed the syscalls (393 onwards) were added on December 31, 2018.

I think only s390 still uses struct passing version of mmap, even though the syscall has been updated and the name is also mmap2. Socket and IPC calls have been modernized.

Thus I'd say let's forget demuxing.

For possible new filtering uses (like examining socket addresses for socket calls or file paths for open etc) the thin wrapper should be useful.

**Comment by pcmoore** [comment]
Based on the discussion above and the fact that we have the notification support in the master branch I think we can close this out, if anyone objects please leave a comment and we can reopen.
