### ISSUE TITLE
RFE: static analysis using scmp_app_inspector

### ISSUE THREAD

**Issue by systmkor** [seccomp/libseccomp#18]
It would be great if the `scmp_app_inspector` tool could run a static analysis scan on a compiled binary to retrieve all of the system calls compiled in, since a dynamic analysis will most likely not catch all of the system calls a program could call (i.e. programmed to call). If gcc debug symbols were required to make the solution simpler that would work as well.

**Comment by pcmoore** [comment]
Agreed, that was/is the eventual idea for the inspector tool.  Unfortunately, it is just so far down on the priority list that I don't see it happening in the near future without some patch submissions from someone else.

You could be that someone ;)

**Comment by systmkor** [comment]
If development of this utility hasn't already begun. I've started on hacking together a tool that would provide this functionality a couple of hours ago.

**Comment by pcmoore** [comment]
No development that I'm aware of beyond the simple strace wrapper in tools/scmp_app_inspector; any help you could provide would be greatly appreciated.

**Comment by pcmoore** [comment]
Any news @systmkor?

Without any serious effort to improve that static inspection tools, I'm tempted to close this issue.  Thoughts @drakenclimber?  My concern is that shared libraries make this a very difficult, and error prone exercise; without any serious dedication to developing a proper tool I see this as a time sink that could distract us from other more important improvements in the core library.

**Comment by drakenclimber** [comment]
> Any news @systmkor?
> 
> Without any serious effort to improve that static inspection tools, I'm tempted to close this issue. Thoughts @drakenclimber? My concern is that shared libraries make this a very difficult, and error prone exercise; without any serious dedication to developing a proper tool I see this as a time sink that could distract us from other more important improvements in the core library.

Over the last few years, I know of a couple efforts to identify all of the syscalls in a given program.  They've all had their share of successes and failures, but for the most part have reached a similar point to `scmp_app_inspector`.  It's just really, really hard to do well.

If someone else has the time to own this, I will gladly cheer them on.  But otherwise, I agree, let's close this.  It's a problem that looks straightforward on the surface but is actually nefariously difficult.

**Comment by pcmoore** [comment]
Okay, I'm going to close this.  @systmkor if you've got something to share, please feel free to reopen this issue - we would love to improve our analysis tools!

**Comment by Hello71** [comment]
i'm thinking of working on something in this area. @drakenclimber could you outline some of the issues involved here? thanks!

**Comment by drakenclimber** [comment]
Sure.

A friend of mine experimented with this a few years back.  His static analyzer started at `main()` and walked through the entire program, branch by branch.  Figuring out the syscalls within the program itself wasn't too bad, but things started to get out of control when the program invoked a library.  Every system update, he needed to re-run the static analyzer because some libraries had changed just enough to break his filter.  Thus the filter was really only good for a single configuration.  I imagine combining something like this with chef/puppet could be pretty useful though.

Finally, to make his experiment even more challenging, he looked into examining the arguments to the syscalls as well.  This involved some really tricky x86 assembly analysis.
