### ISSUE TITLE
RFE: enable automated continuous integration testing

### ISSUE THREAD

**Issue by pcmoore** [seccomp/libseccomp#2]
Patch to enable support for the Travis CI service:

https://groups.google.com/forum/#!topic/libseccomp/wuzIVIwKIvU

**Comment by pcmoore** [comment]
Patch to enable support for the codeship.io service:

https://groups.google.com/forum/#!topic/libseccomp/75xRW_X5SsA

**Comment by androm3da** [comment]
I tried a [couple of different ones mentioned on quora](http://www.quora.com/What-is-the-difference-between-Bamboo-CircleCI-CIsimple-Ship-io-Codeship-Jenkins-Hudson-Semaphoreapp-Shippable-Solano-CI-TravisCI-and-Wercker):
* Travis
* Shippable
* Codeship

Travis seems like a popular one, so it seemed reasonable to start there.  `libseccomp` just can't build there since it uses a distro release that's so old.  Shippable uses a similar/identical build metadata file as Travis'.  Shippable claims to have Ubuntu 13.10 but they don't explicitly support C/C++ (only higher level languages like Java/ruby/python/php/etc).  They probably have incidental support since those languages often provide extension mechanisms that expect to be able to use a compiler and linker.

Codeship uses ubuntu 14.04, and unlike the others offers you no superuser access to the target build node.  Also, its build metadata is stored with your user's account and not with the project.  They offer a convenient ssh-on-demand for build debugging.  This is much more convenient than the git-push-trial-and-error required with the others.

All of them work with Github's API to detect a push or a pull request to trigger a new build.

I decided to try Codeship after failing with Travis.  I designed the CI script in my patch to the mailing list to be pretty generic.  We could invoke it from the Travis or Shippable CI config file.  But at least until Travis updates to a newer release it won't work there.  It may work on Shippable, though.

**Comment by pcmoore** [comment]
The Fedora team also a Jenkins instance for CI which might be another option:

* https://fedoraproject.org/wiki/Jenkins@infra

**Comment by pcmoore** [comment]
Another, easier, first step might to be doing continuous builds using Fedora's Copr infrastructure.

 * https://fedorahosted.org/copr
 * https://copr.fedorainfracloud.org

**Comment by dkopecek** [comment]
FYI: It's possible to get an Ubuntu 14.04 (trusty) environment on Travis CI. Here are the details: https://docs.travis-ci.com/user/trusty-ci-environment/

**Comment by pcmoore** [comment]
Added initial Travis CI support in 47bdf57274ef7e2c48a97de991855efa10c4bf55.  The current Travis configuration tests both the native/C and the Python bindings as well as both the standard and "live" regression tests on Ubuntu Trusty x86_64.

At some point we may want to look at expanding our CI testing to other platforms/architectures, but this is a good first step.  I'm going to close this out, we can track any expanded efforts in new issues/PRs.
