### ISSUE TITLE
RFE: Support for sparc and sh (and possibly other architectures)

### ISSUE THREAD

**Issue by onitake** [seccomp/libseccomp#231]
The Linux kernel supports SECCOMP on sparc/sparc64 and sh, but it seems libseccomp refuses to compile: https://buildd.debian.org/status/fetch.php?pkg=libseccomp&arch=sparc64&ver=2.4.3-1&stamp=1584054619&raw=0
```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../include -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPIC -fvisibility=hidden -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -c arch.c  -fPIC -DPIC -o .libs/libseccomp_la-arch.o
arch.c:101:2: error: #error the arch code needs to know about your machine type
  101 | #error the arch code needs to know about your machine type
      |  ^~~~~
```

HAVE_ARCH_SECCOMP_FILTER is missing on these architectures. Is it required by libseccomp? If SECCOMP is enough, please advise on what needs to be done to add support for these architectures.

Furthermore, does libseccomp really need to depend on the host architecture? Wouldn't it be possible to simply provide stubs that will return an error on unsupported architectures and delegate error handling to the application developer? From what I can see, the `seccomp` syscall is at least defined on many architectures supported by Linux. Calling it will result in -ENOSYS if it's not implemented or disabled.

**Comment by pcmoore** [comment]
A few comments:
* The fact that libseccomp fails to build on sparc/sparc64/sh is a known problem as libseccomp lacks awareness of the architectures/ABIs and as a result it can't function.  Believe it or not, the build failure is a protection mechanism so that people don't attempt to use libseccomp on architectures where it can not function properly.
* For a variety of reasons, libseccomp needs to be aware of a given ABI before it can generate a syscall filter for that ABI.  There are no shortcuts here.
* While libseccomp generates syscall filter independently of the kernel, kernel support is ultimately needed as it is the kernel's responsibility to enforce the syscall filter generated by libseccomp.  Because of this, the kernel MUST have the necessary SECCOMP_FILTER support.

In order to get libseccomp working on sparc/sparc64/sh you will need to add the necessary kernel support first, then we can work on adding support to libseccomp.  I suggest working with the upstream Linux Kernel developers dedicated to the architectures you are interested in; you can find that information in the Linux Kernel's MAINTAINERS file.

**Comment by pcmoore** [comment]
Based on previous experience with similar issues (adding support for a new ABI), I'm going to go ahead and close this issue now, but please feel free to file a new issue when the upstream Linux Kernel has gained SECCOMP_FILTER support for a new ABI.

**Comment by onitake** [comment]
From your response, I gather that libseccomp requires HAVE_ARCH_SECCOMP_FILTER.
Is this correct? SECCOMP (i.e. SECCOMP_SET_MODE_STRICT) alone is not enough?

**Comment by pcmoore** [comment]
Yes, that is correct.  If they ABI doesn't enable HAVE_ARCH_SECCOMP_FILTER then the kernel will not support loading a seccomp BPF filter (the filter that libseccomp generates).

We'll be happy to help you add support to libseccomp once the Linux Kernel gains the necessary support, but as I don't have any sparc/sparc64/sh hardware I'm not really able to help with the kernel side of things.
