### ISSUE TITLE
Q: unable to build qemu-4.2.0 in yocto-poky-3.1.3

### ISSUE THREAD

**Issue by senthilv2k** [seccomp/libseccomp#318]
Hi All,
Am upgrading to yocto-poky-3.1.3 and getting below compilation error.

|..../xrev/tmp/work/x86_64-linux/qemu-system-native/4.2.0-r0/qemu-4.2.0/qemu-seccomp.c:22:10: fatal error: seccomp.h: No such file or directory
|    22 | #include <seccomp.h>
| compilation terminated.

 Any suggestion to fix this issue? Is there any existing fix available for this?

**Comment by senthilv2k** [comment]
@pcmoore could you please help here?

**Comment by pcmoore** [comment]
@senthilv2k you don't have to ping me directly, since I'm watching this project I see all the new issues by default.

Regardless, it sounds like this is either a Yocto problem (not shipping the "seccomp.h" header, or not configuring the QEMU build correctly) or a user problem (you didn't install the necessary prerequisites before trying to build QEMU with libseccomp support.

I am not a Yocto expert, so I would suggest asking this question in a Yocto specific forum or list.  I'll leave this issue open for now, but unless there is a problem with upstream libseccomp (and I'm not sure there is in this case) you'll need to get this sorted with the Yocto folks.

**Comment by senthilv2k** [comment]
Thanks @pcmoore for your reply.
As you suggested, i have raised the query in Yocto forum (https://lists.yoctoproject.org/g/poky/topic/80748567#12358)
I have been asked to "add libsecomp dependency for native".

Not really sure, which file do i need to add libseccomp dependency?
Any suggestion on this?

**Comment by pcmoore** [comment]
As mentioned previously, this is the upstream libseccomp project and we aren't experts in, or even familiar with, all the various Linux based distros.  We try to help when we can, but for help with Yocto I suggest working with the rest of the Yocto community to resolve this problem; we aren't able to help in this case.

I am going to close this issue as it appears to be a problem with Yocto packages and not a general upstream libseccomp problem, but feel free to continue to update the issue with your progress if you see fit.

Thanks, and good luck.
