### ISSUE TITLE
RFE: provide rendered documentation

### ISSUE THREAD

**Issue by Timmmm** [seccomp/libseccomp#357]
It would be helpful if you could provide rendered man pages so you can read the documentation without having to install the library etc.

**Comment by pcmoore** [comment]
We have an open issue for this, please see #83.  We generally don't like to keep multiple issues open on the same thing/topic so I'm going to close this in favor of #83 (it predates this issue and has some history), but if you feel this issue is genuinely different please feel free to comment/re-open and we can discuss further.
