### ISSUE TITLE
Q: syscall using vDSO

### ISSUE THREAD

**Issue by vincentbernat** [seccomp/libseccomp#70]
Hey!

I am trying to intercept some syscalls with libseccomp while they are implemented through vDSO.

```c
seccomp_rule_add(ctx, SCMP_ACT_KILL, SCMP_SYS(clock_gettime), 1,
                         SCMP_A0(SCMP_CMP_EQ, CLOCK_REALTIME))
```

If my clock source is `tsc`, this doesn't kill anything. If this is `acpi_pm`, the process will get killed. Kernel documentation says:

> New code will use the vDSO, and vDSO-issued system calls are indistinguishable from normal system calls.

There is also some stuff about vsyscalls. The documentation seems to say that catching vDSO syscalls should be the same as catching non-vDSO syscalls. Is it a limitation of libseccomp (in the way the BPF filter is built) or a limitation in the kernel or my own fault that I am unable to catch a vDSO-syscall?

**Comment by pcmoore** [comment]
Hello!

The vDSO syscalls are quite interesting; libseccomp will generate filters for these syscalls, but how those filters are run by the kernel can be affected by your architecture and kernel configuration.  I would recommend reading the Linux Kernel's [Documentation/prctl/seccomp_filter.txt file](https://www.kernel.org/doc/Documentation/prctl/seccomp_filter.txt) for more information.

The "Caveats" section is particularly interesting:

    Caveats
    -------

    The vDSO can cause some system calls to run entirely in userspace,
    leading to surprises when you run programs on different machines that
    fall back to real syscalls.  To minimize these surprises on x86, make
    sure you test with /sys/devices/system/clocksource/clocksource0/current_clocksource set to
    something like acpi_pm.
    
    On x86-64, vsyscall emulation is enabled by default.  (vsyscalls are
    legacy variants on vDSO calls.)  Currently, emulated vsyscalls will honor seccomp,
    with a few oddities ...

I'm going to close this issue since it looks like this is the behavior you are describing, and unfortunately there is little we can do about this in libseccomp.  However, if you think there is still a problem here, please feel free to reopen this issue.

Good luck!

**Comment by vincentbernat** [comment]
It took me some time to correctly interpret the first paragraph. It should be read in the context where people are using a whitelist to filter syscalls (which was not my particular case). Therefore, when testing, some syscalls may succeed because seccomp doesn't see them (like `gettimeofday()`), hence the suggestion to test with another clock source.

Thanks for the hint!
