### ISSUE TITLE
Use of seccomp_release()

### ISSUE THREAD

**Issue by pete3215** [seccomp/libseccomp#72]
Manpage:
> Releases  the  seccomp  filter  in  ctx  which was first initialized by seccomp_init(3) or seccomp_reset(3) and frees any memory associated with the given seccomp filter context.  Any seccomp filters loaded into the kernel are not affected.

The manpage of libseccomp shows an example useage of the release function that gets called after the sandboxed code has finished.

However it is not always easy to find all the cases in applications that need to free this memory and I have seen some projects that simple never call seccomp_release.

The most obvious choice would be to simply call seccomp_release() right after seccomp_load().
Is there any catch to this, because the manpage seems to indicate thats how it should be used. But why does the example in the manpage not use it that way.

**Comment by pcmoore** [comment]
The libseccomp library provides an API, it is up to applications to decide how they want to use this API.  Some applications may choose to free the filter immediately, some may choose to keep the filter for future use, and some may keep the filter simply due to poor programming.

You can free the filter via seccomp\_release() as soon as you are done using it, e.g. you've just finished a successful seccomp\_load() call.  The only limitation is that you can't use the filter after you have free'd it.
